PULL_REQUESTS_KEY = "pull_requests"
CHANGED_FILES_KEY = "changed_files"
PR_NUMBER_KEY = "id"
PR_TITLE_KEY = "pr_title"
PR_BODY_KEY = "pr_body"
PR_LABELS_KEY = "pr_labels"
PR_COMMENTS_KEY = "pr_comments"
PR_ISSUE_CLOSED_KEY = "pr_closed_issue"
PR_CHANGED_FILES_KEY = "pr_changed_files"

ISSUE_NUMBER_KEY ="issue_number"
ISSUE_TITLE_KEY = "issue_title"
ISSUE_BODY_KEY = "issue_body"
ISSUE_LABELS_KEY = "issue_labels"
ISSUE_COMMENTS_KEY = "issue_comments"
ISSUE_CLOSED_KEY = "issue_closed"

FILENAME_KEY = "filename"
URL_IN_MAIN_KEY = "url_on_main"
URL_IN_PR_KEY = "url_in_pr"